### PR TITLE
M Specialize delegate map empty value behavior

### LINKED ISSUE #168: IllegalArgumentException: Cannot put empty blob
Hi,

I got the following IllegalArgumentException exception from buildfarm-server:
```
Jun 22, 2018 9:37:52 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@59e50929
java.lang.IllegalArgumentException: Cannot put empty blob
	at build.buildfarm.instance.memory.MemoryLRUContentAddressableStorage.put(MemoryLRUContentAddressableStorage.java:76)
	at build.buildfarm.instance.memory.DelegateCASMap.put(DelegateCASMap.java:51)
	at build.buildfarm.instance.memory.DelegateCASMap.put(DelegateCASMap.java:31)
	at build.buildfarm.instance.AbstractServerInstance.putActionResult(AbstractServerInstance.java:120)
	at build.buildfarm.server.ActionCacheService.updateActionResult(ActionCacheService.java:70)
	at com.google.devtools.remoteexecution.v1test.ActionCacheGrpc$MethodHandlers.invoke(ActionCacheGrpc.java:443)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:271)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:648)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The exception happened with  a3ecfded28723e3cc29ae8efceeddb487a42f99a (latest as of 6/22/2018). 
I can provide a remote grpc log, if that helps.

### PR DESCRIPTION
**Pull request by werkt**
Retain empty-value keys in a time-evicted cache, so that no attempt to
insert an empty value into a ContentAddressableStorage can occur.

Fixes #168

### CODE REVIEW

**Comment by werkt** [comment]
It is simpler, but with content-independent keys, I can end up with an arbitrary number of unique mappings to empty blobs. The delegate map uses eviction in the CAS to trigger eviction in its mapping, and with such an invariant in place, there are an arbitrary number of keys which will never be evicted. Left up long enough, this represents unbounded growth.

Since the nominal overhead of performing an action that produces no output is (hopefully) minimal or constant, I only wanted to retain it for long enough to represent a sensible eviction, and then be assured that we did not pose a consumption risk with a mandatory expiry.

File: src/main/java/build/buildfarm/instance/memory/DelegateCASMap.java [hunk 1]
```diff
@@ -60,16 +74,24 @@ public V get(Object key) {
...
   public boolean containsKey(Object key) {
-    return digestMap.get(key) != null;
+    return digestMap.containsKey(key) || emptyCache.getIfPresent(key) != null;
   }
 
   public V remove(Object key) {
     Digest valueDigest = digestMap.remove(key);
+    if (valueDigest == null) {
+      emptyCache.invalidate(key);
+      valueDigest = digestUtil.empty();
```
Comment (ola-rozenfeld) [inline src/main/java/build/buildfarm/instance/memory/DelegateCASMap.java]: But if it's something that wasn't in the map, aren't you supposed to return null?

Comment (werkt) [reply src/main/java/build/buildfarm/instance/memory/DelegateCASMap.java]: Too right. updated.
