### PR TITLE
M Refine watchOperation behavior and test

### LINKED ISSUE #165: Server watchOperation NPE
Have not had time to investigate deeply but have observed this near the end of a build.

```
Jun 20, 2018 4:39:08 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@357c5d0
java.lang.NullPointerException
	at build.buildfarm.instance.memory.MemoryInstance.watchOperation(MemoryInstance.java:347)
	at build.buildfarm.server.WatcherService.watch(WatcherService.java:69)
	at com.google.watcher.v1.WatcherGrpc$MethodHandlers.invoke(WatcherGrpc.java:237)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:271)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:648)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by werkt**
Protect watchOperation against missing operation requests, watchers
which ignore operation state, and races to operation completions or
expirations. Define watchOperation interface behavior and expectations
for watchers:

watchers will return true if they expect further tests, and false if no
subsequent tests should occur.
watchOperation will return true if the watcher will be tested for all
updates, and false otherwise or if the watcher responds with true in the
terminal cases of missing or done operations.

Fixes #165

### CODE REVIEW

File: src/test/java/build/buildfarm/instance/memory/MemoryInstanceTest.java [hunk 1]
```diff
@@ -158,4 +174,103 @@ public void actionCacheRetrievableByActionKey() {
...
+    List<Predicate<Operation>> operationWatchers =
+        (List<Predicate<Operation>>) mock(List.class);
+    watchers.put(operation.getName(), operationWatchers);
+
+    Predicate<Operation> watcher = (Predicate<Operation>) mock(Predicate.class);
+    assertThat(instance.watchOperation(
+        operation.getName(),
+        /* watchInitialState=*/ false,
+        watcher)).isTrue();
+    verify(operationWatchers, times(1)).add(eq(watcher));
```
Comment (ola-rozenfeld) [inline src/test/java/build/buildfarm/instance/memory/MemoryInstanceTest.java]: Style: prefer not mocking data objects. In this case, you could use an actual list and verify that it .containsExactly(yourItems)
