### PR TITLE
Bug: Fix workerSet update logic for RemoteCasWriter

### LINKED ISSUE #1519: Are workers in RemoteCasWriter fixed whenever any new storage workers are added afterwards?
Hi @werkt, @luxe ,

I encounter a problem when I mix to use storage-only and execution-only workers. When the execution-only workers are initialized before the storage-only workers, they are not able to found the storage-worker to upload results and report

```
SEVERE error uploading outputs for shard/operations/fcfd786c-56fb-4a90-b075-185098a1cf96
java.io.IOException: no available workers
        at build.buildfarm.worker.shard.RemoteCasWriter.getRandomWorker(RemoteCasWriter.java:119)
        at build.buildfarm.worker.shard.RemoteCasWriter.writeToCasMember(RemoteCasWriter.java:83)
        at build.buildfarm.worker.shard.RemoteCasWriter.lambda$insertFileToCasMember$0(RemoteCasWriter.java:71)
        at build.buildfarm.common.grpc.Retrier.execute(Retrier.java:237)
        at build.buildfarm.worker.shard.RemoteCasWriter.insertFileToCasMember(RemoteCasWriter.java:71)
        at build.buildfarm.worker.shard.RemoteCasWriter.write(RemoteCasWriter.java:64)
        at build.buildfarm.worker.shard.ShardWorkerContext.insertFile(ShardWorkerContext.java:454)
        at build.buildfarm.worker.shard.ShardWorkerContext.uploadOutputFile(ShardWorkerContext.java:536)
        at build.buildfarm.worker.shard.ShardWorkerContext.uploadOutputs(ShardWorkerContext.java:684)
        at build.buildfarm.worker.ReportResultStage.reportPolled(ReportResultStage.java:98)
        at build.buildfarm.worker.ReportResultStage.tick(ReportResultStage.java:81)
        at build.buildfarm.worker.PipelineStage.iterate(PipelineStage.java:102)
        at build.buildfarm.worker.PipelineStage.runInterruptible(PipelineStage.java:44)
        at build.buildfarm.worker.PipelineStage.run(PipelineStage.java:51)
        at java.lang.Thread.run(Thread.java:750)
```

my bazel-buildfarm version is 2.6.1

After investigating the source code, I found the RemoteCasWriters' workerSet is [fixed](https://github.com/bazelbuild/bazel-buildfarm/blob/main/src/main/java/build/buildfarm/worker/shard/RemoteCasWriter.java#L51C1-L52C1) after the worker's creation. So if a execution-only worker is initialized before the storage-workers, it is not able to get the storage-worker anymore. Is it as expected ? I feel there should be a mechanism to update the workerSet inside the CasWriter after a new storage-worker bootup ? 

Correct me if I'm wrong, Thanks!

### PR DESCRIPTION
**Pull request by amishra-u**
close #1519

### CODE REVIEW

File: src/main/java/build/buildfarm/worker/shard/RemoteCasWriter.java [hunk 1]
```diff
@@ -114,20 +115,19 @@ public void insertBlob(Digest digest, ByteString content)
...
-      Random rand = new Random();
-      int index = rand.nextInt(workerSet.size());
-      // best case no allocation average n / 2 selection
-      Iterator<String> iter = workerSet.iterator();
-      String worker = null;
-      while (iter.hasNext() && index-- >= 0) {
-        worker = iter.next();
-      }
-      return worker;
+    Set<String> workerSet = backplane.getStorageWorkers();
```
Comment (st0rm23) [inline src/main/java/build/buildfarm/worker/shard/RemoteCasWriter.java:118]: will it cause frequent access to backplane like redis ?  How about adding some logic like
```
if (this.workerSet.isEmpty() || System.currentTimeMillis() > this.lastWorkerUpdateTime + 5000) {
    this.lastWorkerUpdateTime = System.currentTimeMillis();
    this.workerSet = backplane.getStorageWorkers();
}

```

Comment (amishra-u) [reply src/main/java/build/buildfarm/worker/shard/RemoteCasWriter.java:118]: No, this will not cause frequent call to backplace. 
You may read this code to understand better https://github.com/bazelbuild/bazel-buildfarm/blob/938c789dcdd8603eb6bb1d0525a8d891dbb077c0/src/main/java/build/buildfarm/instance/shard/RedisShardBackplane.java#L703

Comment (st0rm23) [reply src/main/java/build/buildfarm/worker/shard/RemoteCasWriter.java:118]: I see, cool!

**Review by jasonschroeder-sfdc — APPROVED** [review]

**Review by werkt — APPROVED** [review]
Glad to have this fix in. We need to have some tests for this as well.
