### PR TITLE
M Switch to Multimap to support watchers

### LINKED ISSUE #180: java.lang.IllegalStateException thrown from MemoryInstance.java
Hi,

`buildfarm-server` gave me the following error.  The source revision I used was 8cdd8f0 (master) with [pull/179](https://github.com/bazelbuild/bazel-buildfarm/pull/179) applied on top it.
```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@76245ff9
java.lang.IllegalStateException
        at build.buildfarm.instance.memory.MemoryInstance.updateOperationWatchers(MemoryInstance.java:167)
        at build.buildfarm.instance.AbstractServerInstance.putOperation(AbstractServerInstance.java:640)
        at build.buildfarm.instance.memory.MemoryInstance.putOperation(MemoryInstance.java:221)
        at build.buildfarm.server.OperationQueueService.put(OperationQueueService.java:91)
        at build.buildfarm.v1test.OperationQueueGrpc$MethodHandlers.invoke(OperationQueueGrpc.java:369)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:271)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:648)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The error reported by `bazel` (0.16) is this:
```
ERROR: /home/ubuntu/driving/src/program/plant_evaluator/plant_only/BUILD:36:1: C++ compilation of rule '//program/plant_evaluator/plant_only:plant_evaluator_test' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Call failed with not retriable error: java.lang.IllegalStateException: Unexpected result of remote execution: no output files.
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:261)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:113)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:132)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:212)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:95)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
	at com.google.devtools.build.lib.rules.cpp.SpawnGccStrategy.execWithReply(SpawnGccStrategy.java:66)
	at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1024)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:978)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:910)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:120)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:763)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:718)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:457)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:513)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:227)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:400)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unexpected result of remote execution: no output files.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.getOperationResponse(GrpcRemoteExecutor.java:97)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$1(GrpcRemoteExecutor.java:173)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:243)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:113)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$2(GrpcRemoteExecutor.java:143)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:243)
```
I used the following parameters:
* `cas_max_size_bytes: 107374182400` (100G) in `server.config.example`
* `cas_cache_max_size_bytes: 107374182400` (100G) in `worker.config.example`
* `execute_stage_width: 32` in `worker.config.example`

All the other parameters were left untouched.

I also used `--jvm_flag=-Xmx120g` to give the server enough heap memory.

I do have a remote grpc log for this, but it's probably too large (700MB) to attach here.

### PR DESCRIPTION
**Pull request by werkt**
watchers collection is cleanly supported by a Multimap of names to
operation predicates. This removes incumbent map->list maintenance
code and reduces the lockspace of watch update procedures.

Fixes #180

### CODE REVIEW

File: src/main/java/build/buildfarm/instance/memory/MemoryInstance.java [hunk 1]
```diff
@@ -253,30 +274,32 @@ protected void enqueueOperation(Operation operation) {
...
-            filteredWatcherCount++;
+    super.updateOperationWatchers(operation);
+
+    Set<Predicate<Operation>> operationWatchers = watchers.get(operation.getName());
+    synchronized (watchers) {
+      for (Predicate<Operation> watcher : operationWatchers) {
+        ListenableFuture<Boolean> stillWatchingFuture = watcherService.submit(new Callable<Boolean>() {
+          @Override
+          public Boolean call() {
+            return watcher.test(operation) && !operation.getDone();
```
Comment (ola-rozenfeld) [inline src/main/java/build/buildfarm/instance/memory/MemoryInstance.java]: Do I understand correctly that this will perform the check+remove only once, but asynchronously? What's the point to doing it asynchronously, then -- if this is called before the operation is completed, then there's an inherent race, and if it's after, then wouldn't doing it synchronously be the same?

Comment (werkt) [reply src/main/java/build/buildfarm/instance/memory/MemoryInstance.java]: The point to the asynchronous here is to limit time under `synchronized (watchers)` - the watcher.test is potentially a lengthy operation - and to disconnect the caller's responsibility to scale with the universal watcher set. Since this synchronization occurs without respect to the operation, queuing the updates for the watchers into an executor service is necessary to avoid undue sequencing of updates. I've seen needless pid and memory exhaustion while waiting for synchronous access to deliver updates during peak execution traffic.

There is no race as far as the watcher is concerned here - this is an update observer, whose delivery content is immutable, and whenever it manages to get the operation update with `done` of `true` out, the watcher proceeds, no matter how much the actual delivery lags. At worst, we'll miss the opportunity to skip an update because we've already got a further state queued.

**Comment by ola-rozenfeld** [comment]
Sorry for being late, this somehow skipped my filters, I thought I approved it!
