### PR TITLE
[Digest] Use a configured digest function instead of hard-coded SHA1.

### LINKED ISSUE #103: INVALID_ARGUMENT: Digest mismatch
Having configured Bazel to use `SHA256` 
```
startup --host_jvm_args=-Dbazel.DigestFunction=SHA256
```
and build farm server to use SHA256 by adding
```
hash_function = SHA256
```

I'm getting the following exception when trying to build using remote build:
```
ERROR: /private/var/tmp/_bazel_ttsugrii/98bcb5c7cfb9e117ec3600033a1548b4/external/com_google_protobuf/BUILD:274:1: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed: com.google.devtools.build.lib.remote.Retrier$RetryException: Out of retries or status not retriable.
	at com.google.devtools.build.lib.remote.ByteStreamUploader$1.failure(ByteStreamUploader.java:245)
	at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload$1.onClose(ByteStreamUploader.java:362)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:339)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusException: INVALID_ARGUMENT: Digest mismatch c2e7bd71bf22cc3aa5b3f24693fb6b9c84ca50cb/2035 <-> 57ad52caebab9999562fde1414d8c3f65d72d993094534f2ccc4e67a5842b84d/2035
	at io.grpc.Status.asException(Status.java:534)
	at com.google.devtools.build.lib.remote.ByteStreamUploader$1.failure(ByteStreamUploader.java:238)
	... 13 more
Target //src/main/java/build/buildfarm:buildfarm-server failed to build
```

The issue is caused by hard-coded SHA1 algorithm used in [DigestUtil::compute](https://github.com/bazelbuild/bazel-buildfarm/blob/master/src/main/java/build/buildfarm/common/DigestUtil.java#L106) function. The fix is trivial and I'm working on a PR with proper tests to prevent future regressions like this.

### PR DESCRIPTION
**Pull request by ttsugriy**
Previously `DigestUtil#compute` function would ignoer the digest
passed to `DigestUtil` constructor and use a hard-coded SHA1,
which is wrong.

This PR unfortunately also has some formatting changes, because
google-java-format was not very happy about existing code :(

Fixes #103

### CODE REVIEW

File: src/test/java/build/buildfarm/common/DigestUtilTest.java [hunk 1]
```diff
@@ -44,4 +45,21 @@ public void canBuildAValidDigest() {
...
+  }
+
+  @Test
+  public void computesSha256Hash() {
+    ByteString content = ByteString.copyFromUtf8("bazel");
+    DigestUtil util = new DigestUtil(DigestUtil.HashFunction.SHA256);
+    Digest digest = util.compute(content);
+    assertThat(digest.getHash())
+        .isEqualTo("aa0e09c406dd0db1a3bb250216045e81644d26c961c0e8c34e8a0354476ca6d4");
+  }
```
Comment (werkt) [inline src/test/java/build/buildfarm/common/DigestUtilTest.java]: no sha1 love?

**Comment by werkt** [comment]
I'll be changing the summary to drop the formatting references as well.

File: src/test/java/build/buildfarm/common/DigestUtilTest.java (hunk 1 above)
Comment (ttsugriy) [reply src/test/java/build/buildfarm/common/DigestUtilTest.java]: oops, will send a separate PR for SHA1 :) thanks for the supersonic review!

**Comment by werkt** [comment]
https://github.com/werkt/bazel-buildfarm/tree/digestUtil-tests actually
already has this, with your tests used as a base now.
